*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call: 
./ldsc.py \
--ref-ld-chr ../SAMPLE_DATA/eur_w_ld_chr/ \
--out ../results/ldsc/STAGE00DATA/median_imputed/not_subsampled/rg/par01 \
--rg ../results/ldsc/STAGE00DATA/median_imputed/not_subsampled/munged/par01.sumstats.gz,,../results/ldsc/face/STAGE00DATA/median_imputed/not_subsampled/munged/par02.sumstats.gz,../results/ldsc/face/STAGE00DATA/median_imputed/not_subsampled/munged/par03.sumstats.gz,../results/ldsc/face/STAGE00DATA/median_imputed/not_subsampled/munged/par04.sumstats.gz,../results/ldsc/face/STAGE00DATA/median_imputed/not_subsampled/munged/par05.sumstats.gz,../results/ldsc/face/STAGE00DATA/median_imputed/not_subsampled/munged/par06.sumstats.gz \
--w-ld-chr ../SAMPLE_DATA/eur_w_ld_chr/ 

Beginning analysis at Wed Mar 16 18:44:43 2022
Reading summary statistics from ../results/ldsc/STAGE00DATA/median_imputed/not_subsampled/munged/par01.sumstats.gz ...
Traceback (most recent call last):
  File "./ldsc/ldsc.py", line 642, in <module>
    sumstats.estimate_rg(args, log)
  File "/usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/python/ldsc/ldscore/sumstats.py", line 397, in estimate_rg
    alleles=True, dropna=True)
  File "/usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/python/ldsc/ldscore/sumstats.py", line 242, in _read_ld_sumstats
    sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)
  File "/usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/python/ldsc/ldscore/sumstats.py", line 163, in _read_sumstats
    sumstats = ps.sumstats(fh, alleles=alleles, dropna=dropna)
  File "/usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/python/ldsc/ldscore/parse.py", line 89, in sumstats
    x = read_csv(fh, usecols=usecols, dtype=dtype_dict, compression=compression)
  File "/usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/python/ldsc/ldscore/parse.py", line 21, in read_csv
    return pd.read_csv(fh, delim_whitespace=True, na_values='.', **kwargs)
  File "/opt/anaconda/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 491, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/anaconda/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 268, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/anaconda/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 583, in __init__
    self._make_engine(self.engine)
  File "/opt/anaconda/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 724, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/anaconda/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 1093, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3253)
  File "pandas/parser.pyx", line 553, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:5584)
  File "/opt/anaconda/anaconda3/envs/ldsc/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '../results/ldsc/STAGE00DATA/median_imputed/not_subsampled/munged/par01.sumstats.gz'

Analysis finished at Wed Mar 16 18:44:43 2022
Total time elapsed: 0.08s
